### ISSUE TITLE
Fejl ved booking af behandlerrum (arbejdsrum OK)

### ISSUE THREAD

**Issue by johantino** [NewCircleMovement/tinkuy#8]
error message when clicking on 'behandlerrum' ... rake task run today (to create timeslots) , works fine on 'arbejdsrum'

**Comment by kbjerring** [comment]
Do we have more output? Looks like all timeslots have been generated for both rooms. I get no error when making a booking.

**Comment by johantino** [comment]
Now it works! ... don't know if you did anything but know it works. Nice :)
... maybe just an update or something ..

On Wed, Jul 15, 2015 at 12:47 PM, Karsten Bjerring Olsen <
notifications@github.com> wrote:

> Do we have more output? Looks like all timeslots have been generated for
> both rooms. I get no error when making a booking.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NewCircleMovement/tinkuy/issues/8#issuecomment-121573847
> .

## 

_Glad_ _vilje_,
Johan Tino

Skype: johantino
LinkedIn: http://www.linkedin.com/in/johantino

   -
