### ISSUE TITLE
Under userprofile: Events-by - button

### ISSUE THREAD

**Issue by johantino** [NewCircleMovement/tinkuy#87]
... showing all the events created by the user logged in ... otherwise active teachers can quickly loose an overview

**Comment by kbjerring** [comment]
Suggest to put this in the user upper right menu
Should teachers also have access to "edit" and "destroy" the events they are admins for?

**Comment by johantino** [comment]
Sounds good! (upper right menu) ... and yes, 'edit' and 'destroy' is also very usable for the events they are admins for ..
